const Map<String, String> am = {
  'app_title': 'ገበሬ እርዳታ',
  'splash_message': 'የተሽጥ የተክል በሽታዎችን በቀላሉ ያውቁ',
  'onboarding_title': 'እንኳን ወደ ገበሬ እርዳታ በደህና መጡ',
  'onboarding_subtitle': 'የተክል ምስል ይይዙ ወይም ይምረጡ በሽታውን ለመገንዘብ',
  'home_camera': 'ካሜራ',
  'home_gallery': 'ማዕከል ምስሎች',
  'home_settings': 'ቅንብሮች',
  'capture_plant_image': 'የተክል ምስል ይቅርቡ',
  'choose_photo': 'ምስል ይምረጡ',
  'plant_analysis': 'የተክል ትንተና',
  'detected_disease': 'የተገኘ በሽታ:',
  'recommended_treatment': 'የተመከረ ሕክምና:',
  'confidence': 'እምነት:',
  'back': 'ተመለስ',
  'no_images_found': 'ምስሎች አልተገኙም',
  'failed_to_take_picture': 'ምስል ማንሳት አልተቻለም።',
  'failed_to_analyze_image': 'ምስሉን ማስተካከል አልተቻለም። እባክዎ ድጋሚ ይሞክሩ።',
  'no_result_found': 'ውጤት አልተገኘም',
};
