const Map<String, String> en = {
  'app_title': 'Farmer Assist',
  'splash_message': 'Detect Plant Diseases Easily',
  'onboarding_title': 'Welcome to Farmer Assist',
  'onboarding_subtitle': 'Capture or choose a plant image to detect disease',
  'home_camera': 'Camera',
  'home_gallery': 'Gallery',
  'home_settings': 'Settings',
  'capture_plant_image': 'Capture Plant Image',
  'choose_photo': 'Choose Photo',
  'plant_analysis': 'Plant Analysis',
  'detected_disease': 'Detected Disease:',
  'recommended_treatment': 'Recommended Treatment:',
  'confidence': 'Confidence:',
  'back': 'Back',
  'no_images_found': 'No images found',
  'failed_to_take_picture': 'Failed to take picture.',
  'failed_to_analyze_image': 'Failed to analyze image. Please try again.',
  'no_result_found': 'No result found',
};
